### PR TITLE
Chl corrections

### PR DESCRIPTION
**Pull request by alexandraqn**
Hi @gronert-m ,

I updated this branch with the latest changes to CHL, it turns out I needed to run the checks only. As before please note the casen webpage is still not working, so that leaves us with a narrow space to interpret the external check results. In addition, note that three files  have flags. First, 1990 has a flag for wage by skill level, for some reason the medium wage is lower on average to the wage of other groups, I am not entirely sure as to why since this is only happening here. It could be the thing with the number of observations by group as we discussed last time. In addition the years 1998 and 2003 give flags for wage by age group (retirees) , I perused the results and indeed the flag relates to the quantity of observations being averaged.  Besides this, the rest of the files have no flags on wages and cover the comments made to the files.

Happy to hear your thoughts on this, 
Alexandra

### CODE REVIEW

**Comment by alexandraqn** [comment]
Hi @gronert-m 
This branch is updated as per revisions requested.
Best,
Alexandra

**Comment by alexandraqn** [comment]
Dear @gronert-m , 
just to let you know that the checks (series and dynamics) are complete and the corresponding do files are available here and the server.
Looking forward to your comments if any,
Alexandra

**Comment by alexandraqn** [comment]
Hi @gronert-m ,
I did one small update . The files should be ready for pull.
Best. 
Alexandra

**Comment by gronert-m** [comment]
Thanks for this! 

Done separately in #432 pull because of some conflicts. Am closing this pull. Please delete this branch at your earliest convenience.

**Pull request closed without merging**
