### PR TITLE
Col v1.1

### PR DESCRIPTION
**Pull request by alexandraqn**
Hi @gronert-m ,

I am sending you the first draft of the 1996-2005 GLD as you suggested using the data from the folder we have. I already checked the data and should have minor flags.

Best regards,

### CODE REVIEW

**Comment by alexandraqn** [comment]
Hi @gronert-m ,

The years 1996 to 2006 are ready for revision. I included the year 2006 using he GEIH harmonisation.

Looking forward to hear your thoughts,

Best,
Alexandra

**Comment by gronert-m** [comment]
Thanks for this @alexandraqn 

I suggest the following amendments:

- ISIC

The data is at letter code (1/17) in all cases. Hence you do not code it as an ISIC code. In that case the isic_version variable should also be missing

However, conveying the fact that industry_orig is at ISIC letter level is important. I suggest adding a not to industry_orig

```
/* <_industry_orig_note>
	Original information at letter code level for ISIC 3(3.1). 

        | #  | A/Z | Name
        | 1  | A   | Agriculture, hunting and forestry
        | 2  | B   | Fishing
        | 3  | C   | Mining and quarrying
        | 4  | D   | Manufacturing
        | 5  | E   | Electricity, gas and water supply
        | 6  | F   | Construction
        | 7  | G   | Wholesale and retail trade; repair of motor vehicles, motorcycles and
personal and household goods
        | 8  | H   | Hotels and restaurants
        | 9  | I   | Transport, storage and communications
        | 10 | J   | Financial intermediation
        | 11 | K   | Real estate, renting and business activities
        | 12 | L   | Public administration and defence; compulsory social security
        | 13 | M   | Education
        | 14 | N   | Health and social work
        | 15 | O   | Other community, social and personal service activities
        | 16 | P   | Activities of private households as employers and undifferentiated production
activities of private households
        | 17 | Q   | Extra-territorial organizations and bodies

        See https://unstats.un.org/unsd/statcom/doc02/isic.pdf for more details

</_industry_orig_note> */
```

- ISCO

I believe at two digits the information is equal to ISCO 68 and thus warrants creating occup_isco.

Compare the occupation in the annex 4 of the manual (starting at page 80 of the pdf) --> https://microdatos.dane.gov.co//catalog/75/download/810/Manual_de_critica_1_trim_ECH.pdf

with the ISCO 1968 structure (page 31 to 39 of the pdf) --> https://www.ilo.org/ilostat-files/ISCO/newdocs-08-2021/Previous%20versions%20of%20ISCO/ISCO-68/ISCO-68%20EN%20Structure%20and%20defnitions.pdf

**Comment by alexandraqn** [comment]
Hi @gronert-m 

I made the changes as requested. For EHN I found that for Isco was the same situation as ECH, so I also included the occup_isco variable.

All has been checked.
Best,

**Comment by gronert-m** [comment]
@alexandraqn thanks for this.

**Pull request merged**
