### PR TITLE
Pull request for India GLD

### PR DESCRIPTION
**Pull request by giofsantos11**
Hi Mario and team,

Here is my first attempt to make a pull request in GitHub. These are all the GLD code files for IND except 1987 (which I am still having trouble with) Please let me know if I am doing it correctly. :)

### CODE REVIEW

**Comment by gronert-m** [comment]
Hi @giofsantos11 , thanks for this!

I think, in terms of bringing in your work onto the platform, this is perfect and it is great to see all your Stata wizardry!

I have a few points I wanted to raise, that I think need to be tackled, but that can be done before or after merging. Namely:

* **Naming of the folder structure**

It seems the GLD codes are stored under the I2D2 folder, not the GLD. You just need to reshuffle in your own directory that GitHub Desktop is mapping and it should do these changes automatically.
Capture2

* **Use of the new preamble**

You used, I believe, the 1993 and 1999 GLD codes I had done as templates. Since then we published the [new template for GLD](https://github.com/worldbank/gld/blob/develop-merge/Support/Templates/GLD_Harmonization_Template.do), that contains a few new things, in particular the section to list the versions of national and international classifications (industry, occupation, educ). Please add the new preamble and check whether there are other things in the new template that should change.

<br></br>
* **Tracking of industry and occupation classification at international level**

The new preamble, as discussed above, shall contain the metadata on the underlying classification version (e.g., NIC 2008). Wherever possible, use the information of these codes to classify the international codes (e.g., `industrycat_isic`) to the degree possible. For example, NIC 2008 ([link to document here](), see screenshot from page 10 below), is a 5 digit code that is equivalent to ISIC revision 4 to the first four digits.

Capture

Thus you may code `industrycat_isic` as `gen industrycat_isic = substr(nic_2008,1,4)` taking into account potential errors (should be uncommon) and the correct zero padding if necessary.

The occupation NOC 2004 is equivalent at the two digit level to ISCO-88 (except that ISCO has code 0 for armed forces and NOC has codes X for "workers not classfied"). 

To the degree that is possible, we should incorporate international information.

**Comment by giofsantos11** [comment]
> Hi @giofsantos11 , thanks for this!
> 
> I think, in terms of bringing in your work onto the platform, this is perfect and it is great to see all your Stata wizardry!
> 
> I have a few points I wanted to raise, that I think need to be tackled, but that can be done before or after merging. Namely:
> 
> * **Naming of the folder structure**
> 
> It seems the GLD codes are stored under the I2D2 folder, not the GLD. You just need to reshuffle in your own directory that GitHub Desktop is mapping and it should do these changes automatically.
> Capture2
> 
> * **Use of the new preamble**
> 
> You used, I believe, the 1993 and 1999 GLD codes I had done as templates. Since then we published the [new template for GLD](https://github.com/worldbank/gld/blob/develop-merge/Support/Templates/GLD_Harmonization_Template.do), that contains a few new things, in particular the section to list the versions of national and international classifications (industry, occupation, educ). Please add the new preamble and check whether there are other things in the new template that should change.
> 
> 
> 
> 
> * **Tracking of industry and occupation classification at international level**
> 
> The new preamble, as discussed above, shall contain the metadata on the underlying classification version (e.g., NIC 2008). Wherever possible, use the information of these codes to classify the international codes (e.g., `industrycat_isic`) to the degree possible. For example, NIC 2008 (link to document here, see screenshot from page 10 below), is a 5 digit code that is equivalent to ISIC revision 4 to the first four digits.
> 
> Capture
> 
> Thus you may code `industrycat_isic` as `gen industrycat_isic = substr(nic_2008,1,4)` taking into account potential errors (should be uncommon) and the correct zero padding if necessary.
> 
> The occupation NOC 2004 is equivalent at the two digit level to ISCO-88 (except that ISCO has code 0 for armed forces and NOC has codes X for "workers not classfied").
> 
> To the degree that is possible, we should incorporate international information.

**Comment by giofsantos11** [comment]
Thanks Mario. Fixed the mix up in the folder location. Will update the do files to include the new preamble and variables harmonizing with international classification systems

**Review by buscandoaverroes — APPROVED** [review]

**Comment by buscandoaverroes** [comment]
Mario's comments make sense to me and good to get an idea of what to look out for in GLD!

**Pull request merged**
