### PR TITLE
Col

### PR DESCRIPTION
**Pull request by alexandraqn**
Dear @gronert-m ,

I updated the survey country information as agreed. I am sending this pull request for the record but we can discuss further tomorrow.

Best,
Alexandra

### CODE REVIEW

**Comment by alexandraqn** [comment]
hi @gronert-m , 
about our discussion today, note that actually I already deleted the link in the section you suggested so this ready for your feedback.
Thanks,
Alexandra

**Comment by gronert-m** [comment]
Intro looks good, I have nothing further to add other than thanks! Let me know when the other parts are ready.

**Comment by alexandraqn** [comment]
Hi @gronert-m 
All is ready for your revision. 
best,

**Comment by alexandraqn** [comment]
Hi @gronert-m ,

I implemented your comment. It should all be fine but let me know if you see anything else that requires checking.
Best,

**Review by gronert-m — APPROVED** [review]

**Comment by gronert-m** [comment]
@alexandraqn Thanks for this. Please delete the branch if no longer necessary.

**Pull request merged**
