### PR TITLE
Expand I2D2 code in new folder structure

### PR DESCRIPTION
**Pull request by buscandoaverroes**

### CODE REVIEW

**Comment by buscandoaverroes** [comment]
I've skipped 2016 due to the recoding and value label issue described in #16 and #17 and #18 , so I will continue with 2018

**Comment by buscandoaverroes** [comment]
pausing here, continue with 19, working on issue #19

**Comment by buscandoaverroes** [comment]
fixed industry codes, now continue expanding more difficult years to harmonize/append using `iecodebook`. I'm keeping in the back of my mind what I've learned in `feature-data-labels` branch from the `retroharmonize` package -- it may be that the right way forward is actually not to use `iecodebook` for but actually `retroharmonize` once I figure out how to do it properly. For the time being, moving along with `iecodebook`.

**Comment by buscandoaverroes** [comment]
returning from diversion in #25: 

- I know that for now the best thing to do is to use the imperfect workflow of `iecodebook`, script with `dplyr` and `openxlsx` to export to the output from iecodebook, then find and replace with the NA values.

**Comment by buscandoaverroes** [comment]
Maybe I should just make a metadata file for all rounds/years and that might help address many issues such at once...

**Comment by buscandoaverroes** [comment]
after trying to recode the education codes for the 2017 file, I noticed that it's such a headache that it really would be good to have in the very least a metadata file. Even if I do nothing more than just browse/create label objects with `dplyr` it would be very helpful for documentation purposes to show how coding schemas of key variables change over time. Branching...

**Comment by gronert-m** [comment]
@buscandoaverroes  can the `feature-expand-i2d2` branch be removed?

**Pull request merged**
