### PR TITLE
Switching documentation to use the jupyter-book structure

### PR DESCRIPTION
**Pull request by elbeejay**
Overhauling the documentation to use the `jupyter-book` format based on the [template](https://github.com/worldbank/template).

Converted the `gld/Support/A - Guides and Documentation/GLD_Manual_V.1.0.docx` file into an `.md` file with [pandoc](https://pandoc.org/) but still need to manually go in and clean up the formatting.

- [x] clean up manual formatting (`.md` file) - will likely need another few passes to catch everything... it's a long file

Similarly, an initial take on dynamic generation of a page with the harmonization script hierarchy and links to each `.do` file has been started, but I need to get the GitHub workflow fixed and check the formatting of the output `.md` file more closely.

- [x] check and finalize formatting for dynamic hierarchy documentation

There are a bunch of stubs and placeholders in the documentation, and some redundancies (multiple locations and files for contributing for example) that I'll attempt to trim down and set some basic information in as well.

- [x] fill-out stubs, delete redundant pages

Will mark this as "Ready" once complete, but wanted to keep you both in the loop @g4brielvs and @gronert-m

### CODE REVIEW

**Comment by g4brielvs** [comment]
@elbeejay Thanks! In regard to build/workflow, it works perfectly, but I'll defer to @gronert-m to review/provide feedback on the content. A preview is available at: https://worldbank.github.io/glddocs (to preserve the [current link](https://worldbank.github.io/gld)).

**Review by g4brielvs — COMMENTED** [review]
In regard to build/workflow, it works!

**Comment by g4brielvs** [comment]
This PR will close #541.

**Comment by elbeejay** [comment]
@gronert-m - we are pending your approval and merge for this documentation to go live.

**Comment by elbeejay** [comment]
@gronert-m what's the plan here? The branch is only going to get more stale and there are only going to be additional conflicts as files change. Is there anything you'd like changed or revised here before this is merged?

**Review by gronert-m — APPROVED** [review]

**Pull request merged**
