### PR TITLE
tur 2003-2004

### PR DESCRIPTION
**Pull request by alexandraqn**
Dear @gronert-m ,
as discussed in my email please find the current branch with the latest updates for turkey.
Best, 
Alexandra

### CODE REVIEW

**Comment by alexandraqn** [comment]
Hi @gronert-m . 
I mad the changes as discussed for all years.
Best,
Alexandra

**Comment by gronert-m** [comment]
@alexandraqn thanks for this. I have three little comments:

1) Please drop the files relating to the quality checks from pull request
image

2) Please add a section on the country survey details explaining the educat choice
The CSD already have a section on education and the changes in the law. What would be great to add is a part where you (a) explain why you went for the more conservative approach of only coding at `educat4` level and (b) propose how to code `educat7` based on `educat_orig` (your original code) if someone so wanted to make it easier for them.

3) Please correct the duplication in the educat4 code
image

**Comment by alexandraqn** [comment]
Hi @gronert-m ,
I made the changes as requested please let me know your thoughts.
Best,
Alexandra

**Comment by alexandraqn** [comment]
Hi @gronert-m ,
I updated this branch as requested.
Let me know if you have further comments.
Best,

**Review by gronert-m — APPROVED** [review]

**Review by gronert-m — APPROVED** [review]

**Pull request merged**
