### PR TITLE
v3 2004 and v2 the rest

### PR DESCRIPTION
**Pull request by alexandraqn**
Hi @gronert-m , 

this is the correct branch , it is a draft because I am yet to address the feedback.

Best,
Alexandra

### CODE REVIEW

**Comment by alexandraqn** [comment]
Hi @gronert-m ,
as discussed, here are the changes requested.
best,
Alexandra

**Comment by alexandraqn** [comment]
Hi @gronert-m ,

Happy to share that I solved the backlog of issues in the branch and that as requested I deleted conflicting q-check files. Now it should not create a conflict. 

Please let me know if there is any other change necessary.

Best,

Alexandra

**Comment by alexandraqn** [comment]
Hi @gronert-m ,

This update is ready but needs an internal discussion before approval. 
Best,
Alexandra

**Comment by gronert-m** [comment]
@alexandraqn is this superseded by #387? If yes, please close

**Pull request closed without merging**
